language: ruby
script: ./script/cibuild
rvm:
  - 2.3.1
sudo: false
cache: bundler
notifications:
  email: false

env:
  global:
    MACHINE_USER_NAME: Andrew
    MACHINE_USER_EMAIL: Andrew.butman@dxc.com
